Dev
stepancar-web-programming/2022-fall-lab-portfolio-markelova-mariya-vladimirovna pull request #3
Opened 2022-11-08 22:11 UTC by mmrkl

2022-11-09 23:41 UTC, stepancar commented on index.html
> +let slideIndex = 0;
Ревью - это процесс в котором сторонний разработчик дает комментарии к коду, происходит коллаборация между двумя разработчиками. Обычно, много внимания уделяется логике, читаемости кода.
В этом ПР есть проблемы, которые могли быть исправлены автоматически ревьюеру не пришлось бы отвлекаться на них. прошу добавить eslint, stylelint в проект чтобы мы могли продолжить ревью

2022-11-11 14:02 UTC, mmrkl reviewed
new_one

2022-11-11 15:24 UTC, mmrkl commented on index.html
> +let slideIndex = 0;
ок

2022-11-11 22:25 UTC, stepancar requested changes
Обратите внимание на количество файлов в этом PR
Оно должно наводить на то что что-то идет не так 😃

2022-11-11 22:59 UTC, mmrkl commented
Да, я понимаю, почему -то при добавлении файловой директории node_modules создался пр и для них… я не понимаю, как это исправить, если честно

2022-11-11 23:43 UTC, stepancar commented
@mmrkl , нужно удалить папку node_modules локально, закоммитить изменения.
Добавить node_modules в .gitignore, закоммитить изменения

2022-11-12 08:27 UTC, stepancar commented
![Screen Shot 2022-11-12 at 12 27 27 AM](https://user-images.githubusercontent.com/2854910/201465591-b20cf99d-b8e1-4082-93ba-2a6632151fc9.png)
Предлагаю пофиксить

2022-11-12 08:30 UTC, stepancar commented on index.html
> +<div class="slideshow-container">
Попробовал понажимать быстро на стрелочки карусели, ожидалось что если нажму 5 раз подряд, то фотографии быстро пролистаются

2022-11-12 17:07 UTC, mmrkl commented on index.html
> +<div class="slideshow-container">
![image](https://user-images.githubusercontent.com/92391145/201485916-8f3b6432-a219-4659-8e3d-987e8b2bf44f.png)
а это с какого устройства если открывать?

2022-11-13 23:30 UTC, stepancar commented on index.html
> +<div class="slideshow-container">
@mmrkl , пока слайдер работает так же непредсказуемо. Чтобы увидеть это загрузите страницу, кликните на стрелочку 5 раз подрял, ждите, заметите как листаются слайды

2022-11-13 23:32 UTC, stepancar commented
> ![Screen Shot 2022-11-12 at 12 27 27 AM](https://user-images.githubusercontent.com/2854910/201465591-b20cf99d-b8e1-4082-93ba-2a6632151fc9.png) Предлагаю пофиксить

![Screen Shot 2022-11-13 at 3 31 47 PM](https://user-images.githubusercontent.com/2854910/201550309-686dd45e-7b1b-499d-bf64-801305309793.png)
Это режим эмуляции iphone 12 pro, но не суть, можно просто сузить браузер до минимальной ширины

2022-11-14 09:19 UTC, mmrkl commented on index.html
> +<div class="slideshow-container">
![image](https://user-images.githubusercontent.com/92391145/201620296-975204c0-d972-44e8-9c05-b5e36281f815.png)
при свертывании браузера, не сдвигается информация. Просто в требованиях к данной лабораторной работе не было сделать сайт адаптивным под телефон. Я попробую. Стрелочки понажимала могу прислать вам видео, где они нормально нажимаются и все делается нормально.  Там каждые 3,5 секунды меняется картинка автоматически, если это не устраивает могу поставить ручное слайдшоу, но если хочется листать, то будут пролистываться картинки. Если есть какие-то еще правки и требования, напишите пожалуйста сразу все, потому что у меня до сих пор грузится коммит (а пошел уже 32 час) с библиотеками node_modules.

2022-11-14 22:14 UTC, mmrkl commented on index.html
> +<div class="slideshow-container">
Я меню переделала, убрала лишнее, чтобы высвечивалась только главная страница с телефона, чтобы можно было просто пролистать и все.

2022-11-17 01:12 UTC, stepancar approved these changes

2022-12-12 18:23 UTC, stepancar commented
@mmrkl , пожалуйста, не забудьте смержить

2022-12-17 03:15 UTC, stepancar commented
@mmrkl , пожалуйста, смержите ПР

2022-12-28 21:52 UTC, stepancar commented
@mmrkl , не забудьте смержить пр до 31 декабря

2022-12-29 08:36 UTC, merged

2022-12-29 08:46 UTC, mmrkl commented
Здравствуйте, у меня долгое время не мержилось, все  время писал warning, вроде сделано